from decimal import *
from datetime import *
from typing import *
from marshmallow import Schema, fields, post_load
from openfabric_pysdk.utility import SchemaUtil



################################################################
# VisualqaInput concept class - AUTOGENERATED
################################################################
class VisualqaInput:
    image: str = None
    question: str = None
    

################################################################
# VisualqaInputSchema concept class - AUTOGENERATED
################################################################
class VisualqaInputSchema(Schema):
    image = fields.String()
    question = fields.String()
    
    
    @post_load
    def create(self, data, **kwargs):
        return SchemaUtil.create(VisualqaInput(), data)