from decimal import *
from datetime import *
from typing import *
from marshmallow import Schema, fields, post_load
from openfabric_pysdk.utility import SchemaUtil


################################################################
# LlmsInput concept class - AUTOGENERATED
################################################################
class LlmsInput:
    inputText: str = None
    language: str = None
    link: str = None
    file: str = None
    length_summary: str = None
    operationType: str = None
    systemPrompt: str = None


################################################################
# LlmsInputSchema concept class - AUTOGENERATED
################################################################
class LlmsInputSchema(Schema):
    inputText = fields.String(allow_none=True)
    language = fields.String(allow_none=True)
    link = fields.String(allow_none=True)
    file = fields.String(allow_none=True)
    length_summary = fields.String(allow_none=True)
    operationType = fields.String(allow_none=True)
    systemPrompt = fields.String(allow_none=True)

    @post_load
    def create(self, data, **kwargs):
        return SchemaUtil.create(LlmsInput(), data)