from decimal import *
from datetime import *
from typing import *
from marshmallow import Schema, fields, post_load
from openfabric_pysdk.utility import SchemaUtil



################################################################
# MultiConfig concept class - AUTOGENERATED
################################################################
class MultiConfig:
    name: str = None
    

################################################################
# MultiConfigSchema concept class - AUTOGENERATED
################################################################
class MultiConfigSchema(Schema):
    name = fields.String()
    
    
    @post_load
    def create(self, data, **kwargs):
        return SchemaUtil.create(MultiConfig(), data)
